# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 306ddefd341e53f28965bffd4ae19cb8f672f40e7a9f1878242bde328939144364f0d1984834a1de5e772295018c16830925a084eaf9ee1fbb5864fed21592cc

test:
  secret_key_base: da4768f86ef7ee73330e09d127294ab552c8c6f341c87e50b00acb1878bc9520dc68eb139841a71667f8d9c42fffc5ad135f98379f6d0088bf6470c34a3089bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
